{% set name = "wemake-python-styleguide" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wemake_python_styleguide-{{ version }}.tar.gz
  sha256: 0964cf40ac4d3f1c89dd79aee4b6edba9a1806fb395836c73e746fe287dbae3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core >=1.9.0
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - flake8 >=7.0.0,<8.0.0
    - attrs
    - setuptools
    - typing_extensions >=4.0,<5.0
    - astor >=0.8.0,<0.9.0
    - pygments >=2.4.0,<3.0.0
    - flake8-commas >=2.0.0,<3.0.0
    - flake8-quotes >=3.0.0,<4.0.0
    - flake8-comprehensions >=3.1.0,<4.0.0
    - flake8-docstrings >=1.3.0,<2.0.0
    - flake8-string-format >=0.3.0,<0.4.0
    - flake8-bugbear >=24.2.0,<25.0.0
    - flake8-debugger >=4.0.0,<5.0.0
    - flake8-isort >=6.0.0,<7.0.0
    - flake8-eradicate >=1.5.0,<2.0.0
    - flake8-bandit >=4.1.0,<5.0.0
    - flake8-broken-line >=1.0.0,<2.0.0
    - flake8-rst-docstrings >=0.3.0,<0.4.0
    - pep8-naming >=0.13.0,<0.14.0
    - darglint >=1.2.0,<2.0.0

test:
  imports:
    - wemake_python_styleguide
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://wemake-python-styleguide.rtfd.io
  summary: The strictest and most opinionated python linter ever
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - luftuq
